#pragma once

#include <algorithm>
#include <cstddef>
#include <functional>
#include <utility>
#include <vector>

#include "auto_search_frame/detail/differential_best_search_types.hpp"
#include "auto_search_frame/detail/linear_best_search_types.hpp"

namespace TwilightDream::auto_search_frame::detail
{
	template<typename SearchWeightT>
	static inline void normalize_remaining_round_lower_bound_table(
		std::vector<SearchWeightT>& table,
		int round_count,
		SearchWeightT infinite_weight )
	{
		if ( table.empty() )
		{
			table.assign( std::size_t( std::max( 0, round_count ) ) + 1u, SearchWeightT( 0 ) );
			return;
		}

		if ( table.size() < 1u )
			table.resize( 1u, SearchWeightT( 0 ) );
		table[ 0 ] = SearchWeightT( 0 );

		const std::size_t need = std::size_t( std::max( 0, round_count ) ) + 1u;
		if ( table.size() < need )
			table.resize( need, SearchWeightT( 0 ) );

		for ( SearchWeightT& weight : table )
		{
			if ( weight >= infinite_weight )
				weight = SearchWeightT( 0 );
		}
	}
}  // namespace TwilightDream::auto_search_frame::detail

namespace TwilightDream::auto_search_linear
{
	struct LinearRemainingRoundLowerBoundBootstrapStatus
	{
		bool disabled_due_to_strict = false;
		bool autogenerated = false;
		bool used_non_strict_generation = false;
	};

	inline std::vector<SearchWeight> generate_linear_remaining_round_lower_bound_table(
		const LinearBestSearchConfiguration& base_configuration,
		std::uint32_t start_output_branch_a_mask,
		std::uint32_t start_output_branch_b_mask )
	{
		const int round_count = std::max( 0, base_configuration.round_count );
		std::vector<SearchWeight> table( std::size_t( round_count ) + 1u, 0 );
		if ( round_count <= 0 )
			return table;

		for ( int k = 1; k <= round_count; ++k )
		{
			LinearBestSearchConfiguration config = base_configuration;
			config.search_mode = SearchMode::Strict;
			config.round_count = k;
			config.enable_remaining_round_lower_bound = false;
			config.remaining_round_min_weight.clear();
			config.auto_generate_remaining_round_lower_bound = false;
			config.target_best_weight = INFINITE_WEIGHT;
			// Auxiliary runs use this same Matsui cursor, so they keep the caller-selected
			// exact var-var polarity instead of silently rewriting it.
			config.varvar_modular_add_bnb_mode = base_configuration.varvar_modular_add_bnb_mode;
			// Make the lower-bound search as complete as possible by removing heuristic caps.
			config.maximum_round_predecessors = 0;
			config.maximum_injection_input_masks = 0;

			LinearBestSearchRuntimeControls runtime_controls {};
			runtime_controls.maximum_search_nodes = base_configuration.remaining_round_lower_bound_generation_nodes;
			runtime_controls.maximum_search_seconds = base_configuration.remaining_round_lower_bound_generation_seconds;

			LinearBestSearchContext tmp_context {};
			tmp_context.configuration = config;
			tmp_context.runtime_controls = runtime_controls;
			tmp_context.start_output_branch_a_mask = start_output_branch_a_mask;
			tmp_context.start_output_branch_b_mask = start_output_branch_b_mask;
			begin_linear_runtime_invocation( tmp_context );
			tmp_context.memoization.initialize( std::size_t( config.round_count ) + 1u, config.enable_state_memoization, "linear_memo.lb.init" );

			LinearSearchCursor cursor {};
			LinearSearchFrame  frame {};
			frame.stage = LinearSearchStage::Enter;
			frame.trail_size_at_entry = tmp_context.current_linear_trail.size();
			frame.state.round_boundary_depth = 0;
			frame.state.accumulated_weight_so_far = 0;
			frame.state.round_output_branch_a_mask = start_output_branch_a_mask;
			frame.state.round_output_branch_b_mask = start_output_branch_b_mask;
			cursor.stack.push_back( frame );
			ScopedRuntimeTimeLimitProbe time_probe( tmp_context.runtime_controls, tmp_context.runtime_state );
			linear_best_search_continue_from_cursor( tmp_context, cursor );

			if ( tmp_context.best_weight < INFINITE_WEIGHT )
				table[ std::size_t( k ) ] = tmp_context.best_weight;
		}

		return table;
	}

	template<typename Generator>
	static inline LinearRemainingRoundLowerBoundBootstrapStatus prepare_linear_remaining_round_lower_bound_table(
		LinearBestSearchConfiguration& configuration,
		int round_count,
		Generator&& generator )
	{
		LinearRemainingRoundLowerBoundBootstrapStatus status {};
		if ( !configuration.enable_remaining_round_lower_bound )
			return status;

		const bool generation_limited =
			configuration.auto_generate_remaining_round_lower_bound &&
			( configuration.remaining_round_lower_bound_generation_nodes != 0 ||
			  configuration.remaining_round_lower_bound_generation_seconds != 0 );
		if ( generation_limited && configuration.strict_remaining_round_lower_bound )
		{
			configuration.enable_remaining_round_lower_bound = false;
			configuration.remaining_round_min_weight.clear();
			status.disabled_due_to_strict = true;
			return status;
		}
		if ( generation_limited &&
			 configuration.auto_generate_remaining_round_lower_bound &&
			 configuration.remaining_round_min_weight.empty() )
		{
			status.used_non_strict_generation = true;
		}

		if ( configuration.remaining_round_min_weight.empty() && configuration.auto_generate_remaining_round_lower_bound )
		{
			configuration.remaining_round_min_weight = std::invoke( std::forward<Generator>( generator ) );
			status.autogenerated = true;
		}

		TwilightDream::auto_search_frame::detail::normalize_remaining_round_lower_bound_table(
			configuration.remaining_round_min_weight,
			round_count,
			INFINITE_WEIGHT );
		return status;
	}

	static inline LinearRemainingRoundLowerBoundBootstrapStatus prepare_linear_remaining_round_lower_bound_table(
		LinearBestSearchConfiguration& configuration,
		int round_count,
		std::uint32_t start_output_branch_a_mask,
		std::uint32_t start_output_branch_b_mask )
	{
		return prepare_linear_remaining_round_lower_bound_table(
			configuration,
			round_count,
			[&]() {
				return generate_linear_remaining_round_lower_bound_table(
					configuration,
					start_output_branch_a_mask,
					start_output_branch_b_mask );
			} );
	}
}  // namespace TwilightDream::auto_search_linear

namespace TwilightDream::auto_search_differential
{
	static inline void prepare_differential_remaining_round_lower_bound_table(
		DifferentialBestSearchConfiguration& configuration,
		int round_count )
	{
		if ( !configuration.enable_remaining_round_lower_bound )
			return;

		TwilightDream::auto_search_frame::detail::normalize_remaining_round_lower_bound_table(
			configuration.remaining_round_min_weight,
			round_count,
			INFINITE_WEIGHT );
	}
}  // namespace TwilightDream::auto_search_differential
